// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package main

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./configs", "default.yml", "\"IyBkZWZhdWx0CmFwcDogdmlwZXItdGVzdApkYjoKICB1cmk6IHBvc3RncmVzOi8vdHJlZTpteXB3ZEAxMjcuMC4wLjE6NTQzMi92aXBlci10ZXN0P2Nvbm5lY3RfdGltZW91dD01JnNzbG1vZGU9ZGlzYWJsZQogIHBvb2xTaXplOiAxMDA=\"")
	packr.PackJSONBytes("./configs", "production.yml", "\"IyBwcm9kdWN0aW9uCmRiOgogIHVyaTogcG9zdGdyZXM6Ly90cmVlOm15cHdkQDEwLjEuMS4xOjU0MzIvdmlwZXI/Y29ubmVjdF90aW1lb3V0PTUmc3NsbW9kZT1kaXNhYmxl\"")
	packr.PackJSONBytes("./configs", "test.yml", "\"IyB0ZXN0\"")
}
